// Writes glyph/level/vectors.json from the server's run rules
// (deploy/racer/api/glyph/_lib/runner.js). The Unity port (RunnerSim.cs) must
// reproduce every vector exactly; CI checks both sides.
// Usage: node tools/glyph-vectors.mjs
import fs from "node:fs";

import { generateRows, JUMP, LEFT, RIGHT, SLIDE, simulate } from "../deploy/racer/api/glyph/_lib/runner.js";
import { playBot } from "../deploy/racer/test/glyph-bot.mjs";

const rowSeeds = [0, 1, 42, 7919, 2654435761, 4294967295];
const rows = rowSeeds.map((seed) => ({ seed, count: 400, cells: Array.from(generateRows(seed, 400)).join("") }));

const runs = [];
const record = (name, seed, inputs, endTick) => runs.push({ name, seed, endTick, inputs, expect: simulate(seed, inputs, endTick) });

record("no inputs runs into the first wall", 42, [], 3000);
const full = playBot(31337, { maxTicks: 9000 });
record("bot survives 150 s", 31337, full.inputs, full.endTick);
const blind = playBot(99, { maxTicks: 36000, blindAfterRow: 180 });
record("bot stops dodging after row 180", 99, blind.inputs, 36000);
const late = playBot(4294967295, { maxTicks: 36000, blindAfterRow: 900 });
record("bot dies at top speed", 4294967295, late.inputs, 36000);
record("lane changes clamp at the edges and cancel", 7919, [[0, LEFT], [1, LEFT], [2, LEFT], [10, RIGHT], [11, RIGHT], [12, LEFT], [40, RIGHT], [41, RIGHT], [42, RIGHT]], 2000);
record("jump and slide cannot overlap", 7919, [[100, JUMP], [110, SLIDE], [129, JUMP], [130, SLIDE], [161, JUMP], [190, SLIDE]], 400);

const out = new URL("../glyph/level/vectors.json", import.meta.url);
fs.mkdirSync(new URL(".", out), { recursive: true });
fs.writeFileSync(out, JSON.stringify({ about: "Generated by tools/glyph-vectors.mjs; do not edit.", rows, runs }) + "\n");

// The same vectors as whitespace-separated lines, for the C# side:
//   ROWS <seed> <count> <cells>
//   RUN <seed> <endTick> <inputCount> (<tick> <action>)* <endTick> <died 0|1> <deathRow> <distanceMm> <collectedCount> (<row> <type>)*
const lines = [
  ...rows.map((r) => `ROWS ${r.seed} ${r.count} ${r.cells}`),
  ...runs.map((r) => {
    const e = r.expect;
    return ["RUN", r.seed, r.endTick, r.inputs.length, ...r.inputs.flat(), e.endTick, e.died ? 1 : 0, e.deathRow, e.distanceMm, e.collected.length, ...e.collected.flat()].join(" ");
  }),
];
fs.writeFileSync(new URL("vectors.txt", out), lines.join("\n") + "\n");
for (const run of runs) {
  const e = run.expect;
  console.log(`${run.name}: ${e.died ? `died at row ${e.deathRow}` : "alive"}, tick ${e.endTick}, ${(e.distanceMm / 1000).toFixed(0)} m, ${e.collected.length} runes`);
}
